# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AALc_rgC04POe18O0LKFRm4ouQpLtL3riscEmWp-Q";
    path = fetchzip {
      url = "https://www.sqlite.org/2026/sqlite-amalgamation-3530200.zip";
      hash = "sha256-V+uqp0TCOneh57ECQU33LAQP5xewnWyMisYZjSD9qcc=";
    };
  }
  {
    name = "uucode-0.2.0-ZZjBPlK5VADj7fdoq7G8LIHzD5o6FSkcBXXrRWr4jnrA";
    path = fetchgit {
      url = "https://github.com/jacobsandlund/uucode";
      rev = "2826a37a4562284fdacd8fa029d49509cc9bffcd";
      hash = "sha256-R5RXW5tWIaDq5JOF2+oWd5YOYOyns6WH7f687WE+b20=";
    };
  }
  {
    name = "vaxis-0.6.0-BWNV_EojCgAHV2Lvn5hO22DPkmB1YRlswBIvavDqmP8K";
    path = fetchgit {
      url = "https://github.com/rockorager/libvaxis";
      rev = "a12e9c3046247b6e2e877bf1dcb3806929ecb01a";
      hash = "sha256-52jFyhmoJlzf89pLhB23Kb0t5YK2/+ZfLRYboIoD56g=";
    };
  }
  {
    name = "zeit-0.9.0-5I6bk2m9AgBSMH8-L6rYJkwuQAyhXplnfxnvTSGzVHUR";
    path = fetchgit {
      url = "https://github.com/rockorager/zeit";
      rev = "b1c1c2fcbc71fd7799a316bbcf0ff88d06d80ccc";
      hash = "sha256-2hOyrKTk8nYdkhYC5vpDgkpzJ4QPA8Xy5+Nn2Rd6NB0=";
    };
  }
  {
    name = "zigimg-0.1.0-8_eo2oyaFwBZwJpmqPkCfVXWBrHcqbYwmrp1I6bTD3lI";
    path = fetchgit {
      url = "https://github.com/zigimg/zigimg";
      rev = "d695acd97c02e57bb151e8f659d1280f5cd6ca70";
      hash = "sha256-0IYATQldT6eJxRR2T/2CsIYZuzomqjvmdVyjmsjguyE=";
    };
  }
  {
    name = "ziglint-0.5.2-t0bwLwqTBQALZYj3JDnOW03lrsuRqIWHXioRtkN0D7tn";
    path = fetchgit {
      url = "https://github.com/rockorager/ziglint";
      rev = "90dca75f6301706f925c76c71aff58358758d923";
      hash = "sha256-2eDv9DVTUFSitUJRdXU6EqTk/0eYGEWjIpDMvIEvPA8=";
    };
  }
]
